### ISSUE TITLE
Solara website Python errors

### ISSUE THREAD

**Issue by platinops** [widgetti/solara#122]
I have noticed that the Solara website does not seem to gracefully handle Python errors.

For example:
* Go to https://solara.dev/docs/tutorial/data-science
* Scroll to last chart
* Click on a point
* Set the Y-axis to "Species"

Result:
``` python
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 171, in _na_arithmetic_op
    result = func(left, right)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/computation/expressions.py", line 70, in _evaluate_standard
    return op(a, b)
TypeError: unsupported operand type(s) for -: 'str' and 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1647, in _render
    root_element = el.component.f(*el.args, **el.kwargs)
  File "app.ipynb input cell 21", line 20, in Page
  File "app.ipynb input cell 21", line 6, in find_nearest_neighbours
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/ops/common.py", line 81, in new_method
    return method(self, other)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/arraylike.py", line 194, in __sub__
    return self._arith_method(other, operator.sub)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/series.py", line 6108, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/base.py", line 1348, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 232, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 178, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 135, in _masked_arith_op
    result[mask] = op(xrav[mask], y)
TypeError: unsupported operand type(s) for -: 'str' and 'float'
```

**Comment by maartenbreddels** [comment]
Thanks for reporting.

I added 9c258e1bb2f4dbf1094d5c8d732b492a8a56f45d so that it does not tear down the full page.
I'll keep this open because it is a bug in the example of this tutorial. This might be a good opportunity to write something about this bug, and how simple 2 way binding is often not enough. Food for thought...
