### ISSUE TITLE
TypeError: set_parent() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by jicastillow** [widgetti/solara#145]
When trying the First script example on the Quickstart of the docs, it works correctly when executed on Jupyter notebook, but it won't work as a script directly executed via solara executable.

When doing:

**solara run .\first_script.py**

the server starts but then it keeps logging the following error:

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 254, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\starlette\middleware\gzip.py", line 26, in __call__
    await self.app(scope, receive, send)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\solara\server\starlette.py", line 197, in kernel_connection
    await thread_return
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\anyio\to_thread.py", line 34, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\solara\server\starlette.py", line 190, in websocket_thread_runner
    anyio.run(run)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\anyio\_core\_eventloop.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\anyio\_backends\_asyncio.py", line 204, in run
    return native_run(wrapper(), debug=debug)
  File "c:\users\jicas\anaconda3\envs\ml\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "c:\users\jicas\anaconda3\envs\ml\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\anyio\_backends\_asyncio.py", line 199, in wrapper
    return await func(*args)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\solara\server\starlette.py", line 182, in run
    await server.app_loop(ws_wrapper, session_id, connection_id, user)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\solara\server\server.py", line 148, in app_loop
    process_kernel_messages(kernel, msg)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\solara\server\server.py", line 179, in process_kernel_messages
    kernel.set_parent(None, msg)
  File "c:\users\jicas\anaconda3\envs\ml\lib\site-packages\solara\server\kernel.py", line 294, in set_parent
    super().set_parent(ident, parent, channel)
TypeError: set_parent() takes 3 positional arguments but 4 were given

Is there anything I can do to avoid this error?

Thanks in advance.

**Comment by maartenbreddels** [comment]
Hi, thanks for the report. Which version of ipykernel do you have?

**Comment by jicastillow** [comment]
Hi, the installed version of ipykernel is  5.3.4

**Comment by maartenbreddels** [comment]
OK, thank you. A similar issue was fixed in https://github.com/widgetti/solara/commit/642dc2691507cf73860420003e8009d330cef11b 
A workaround for now is to upgrade to 6, but we'll fix this soon anyway.
Thank you!

**Comment by jicastillow** [comment]
Thanks @maartenbreddels, updated to v6 and it works now!
Great project BTW!

**Comment by maartenbreddels** [comment]
Thank you very much. Feel free to join us on discord!
