### ISSUE TITLE
Hot-reload error: PyO3 modules may only be initialized once per interpreter process

### ISSUE THREAD

**Issue by jonmmease** [widgetti/solara#148]
For an app that uses the `VegaFusionWidget`, the first app render works well, but after editing the file the hot-reload step fails with this Python error:

```
No such comm: 25f3ea8b-a865-4a0c-b55e-8db9e4613d42
ERROR:    Uncaught exception: Traceback (most recent call last):
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 220, in m
    return(method(self, *args, **kwargs))
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 773, in _handle_msg
    self.set_state(state)
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 650, in set_state
    with self._lock_property(**sync_data), self.hold_trait_notifications():
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/traitlets/traitlets.py", line 1502, in hold_trait_notifications
    self.notify_change(change)
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 701, in notify_change
    super().notify_change(change)
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/traitlets/traitlets.py", line 1517, in notify_change
    return self._notify_observers(change)
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/traitlets/traitlets.py", line 1564, in _notify_observers
    c(event)
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/vegafusion_jupyter/widget.py", line 95, in _handle_message
    response_bytes = runtime.process_request_bytes(
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/vegafusion/runtime.py", line 128, in process_request_bytes
    return self.embedded_runtime.process_request_bytes(request)
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/vegafusion/runtime.py", line 53, in embedded_runtime
    from vegafusion_embed import PyVegaFusionRuntime
  File "/Users/jonmmease/miniconda3/envs/try_solara/lib/python3.10/site-packages/vegafusion_embed/__init__.py", line 1, in <module>
    from .vegafusion_embed import *
ImportError: PyO3 modules may only be initialized once per interpreter process
```

[PyO3](https://pyo3.rs/) is the Rust library that use used to wrap VegaFusion in a Python API.  This probably isn't a bug in Solara, VegaFusion, or PyO3. Just some incompatible assumptions across the libraries.  I wanted to bring it up here in case anything comes to mind on how Solara or VegaFusion could work around it.

**Comment by maartenbreddels** [comment]
Hi Jon,

thanks for opening this. Yes, we also see this with other libraries. I think we should change our reload strategy, or at least make it configurable. Hope I can take a look at this soon!

Regards,

Maarten
