### ISSUE TITLE
hot reload and polars

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#197]
consider the following MWE:

```python
import polars as pl
import solara

DATAFRAME = pl.DataFrame(dict(a=range(10)))


@solara.component
def Page():
    solara.Markdown(str(len(DATAFRAME)))

```

Then, to trigger hot reload, add a comment somewhere.
This gives the following error:
```
UserWarning: polars binary missing!
Traceback (most recent call last):
  File "C:\...\site-packages\solara\server\app.py", line 446, in load_app_widget
    widget, render_context = _run_app(
  File "C:\...\site-packages\solara\server\app.py", line 394, in _run_app
    main_object = app_script.run()
  File "C:\...\site-packages\solara\server\app.py", line 197, in run
    self._first_execute_app = self._execute()
  File "C:\...\site-packages\solara\server\app.py", line 114, in _execute
    routes = [solara.autorouting._generate_route_path(self.path, first=True)]
  File "C:\...\site-packages\solara\autorouting.py", line 488, in _generate_route_path
    module = source_to_module(subpath)
  File "C:\...\site-packages\solara\autorouting.py", line 36, in source_to_module
    exec(ast, mod.__dict__)
  File "C:\...\myapp.py", line 4, in <module>
    DATAFRAME = pl.read_csv(
  File "C:\...\site-packages\polars\io\csv\functions.py", line 354, in read_csv
    df = pl.DataFrame._read_csv(
  File "C:\...\site-packages\polars\dataframe\frame.py", line 776, in _read_csv
    self._df = PyDataFrame.read_csv(
NameError: name 'PyDataFrame' is not defined
```

The app still works, but this breaks hot reload in all sort of weird ways down the line (I'm getting error of methods missing on objects which are from different objects)

**Comment by Jhsmit** [comment]
duplicate of #177

**Comment by maartenbreddels** [comment]
Yes, we didn't release it yet

**Comment by koenvo** [comment]
Is this already released? Just check with latest (1.37.0) release and still get the issue.

**Comment by maartenbreddels** [comment]
Ah, thanks for the report! 
I guess we should have a condition that it is in the root path, but not behind sys.prefix
Do you want to open a PR?

**Comment by koenvo** [comment]
Oh yes, let me create a PR.
