### ISSUE TITLE
`@component_vue` with argument names shadowing python built-ins

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#258]
Consider the following example of a tree view with `open` and `active` props synced to solara reactives:

```python
import solara

items = [
    {
        "name": "Measurement_1",
        "icon": "",
        "children": [
            {
                "name": "Fruit",
                "icon": "mdi-lightbulb",
                "children": [
                    {"name": "Node 1.1", "id": 5},
                    {"name": "Node 1.2", "id": 4, "icon": "mdi-delete"},
                ],
                "id": 2,
            },
        ],
        "id": 1,
    }
]


@solara.component_vue("my_treeview.vue")
def MyTreeview(items, value, active, open):
    pass


act = solara.reactive(None)
val = solara.reactive(None)
open = solara.reactive(None)


@solara.component
def Page():
    print("act", act.value)
    print("val", val.value)  # requires selectable
    print("open", open.value)

    MyTreeview(
        items=items,
        value=val.value,
        on_value=val.set,
        active=act.value,
        on_active=act.set,
        open=open.value,
        on_open=open.set,
    )

    solara.Button("set open", on_click=lambda: open.set([1, 2]))

```

my_treeview.vue

```js
<template>
    <v-treeview 
        :items="items" 
        dense 
        hoverable
        activatable
        selectable
        v-model="value" 
        @update:active="value => active = value"
        :open="open"
        @update:open="value => open = value"
        >
        
        <template v-slot:prepend="{ item }">
            <v-icon v-if="item.icon">{{ item.icon }}</v-icon>
        </template>
    </v-treeview>
</template>
```

This gives the following traceback:

```
Traceback (most recent call last):
  File "C:\Users\jhsmi\pp\do-fret\.venv\lib\site-packages\reacton\core.py", line 364, in _create_widget
    widget = self.component.widget(**kwargs)
  File "C:\Users\jhsmi\pp\do-fret\.venv\lib\site-packages\ipyvue\VueTemplateWidget.py", line 146, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\jhsmi\pp\do-fret\.venv\lib\site-packages\ipywidgets\widgets\widget.py", line 506, in __init__
    self.open()
TypeError: 'list' object is not callable
```
probably because `open` argument shadows the python builtin `open`

A workaround is to rename the argument `open` to something else, eg `open_`, the vue template then becomes:
```js 
      :open="open_"
      @update:open="value => open_ = value"
```

The workaround might be considered the solution for the issue

**Comment by maartenbreddels** [comment]
Hi Jochem,

Thanks for the issue. I think the problem is not per se builtins, but a method already used in the widget class. I think we should check those and give a proper error message.
What do you think?

Cheers,

Maarten

**Comment by Jhsmit** [comment]
Yes I agree, confusion is the problem here, a message with instruction to change the name would help
