### ISSUE TITLE
solara.dev/apps/scatter raises AssertionError

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#33]
At the moment, when I visit https://solara.dev/apps/scatter on firefox, I briefly see the web page correctly but then I get the traceback posted below.

The same occurs in chrome or in incognito window.
The other full screen apps are working.

```
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1710, in _reconsolidate
    kwargs = reconsolidate_children()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1678, in reconsolidate_children
    new_kwargs = self._visit_children_values(kwargs, key, parent_key, self._reconsolidate)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in _visit_children_values
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in <dictcomp>
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in _visit_children_values
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in <listcomp>
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1899, in _visit_children_values
    return f(value, key, parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1794, in _reconsolidate
    self._remove_element(self.context.elements[key], key, parent_key=parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1845, in _remove_element
    self._remove_element(self.context.root_element, "/", parent_key=new_parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1861, in _remove_element
    assert widget.model_id in widgets.Widget.widgets
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1838, in _remove_element
    effect.cleanup()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 968, in cleanup
    self._cleanup()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/solara/hooks/dataframe.py", line 45, in cleanup
    listener()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/solara/hooks/dataframe.py", line 35, in on_change
    updater()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/solara/hooks/misc.py", line 355, in updater
    set_counter(lambda count: count + 1)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1154, in set_
    self.render(self.element, self.container)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1271, in render
    widget = self._reconsolidate(self.element, default_key="/", parent_key=ROOT_KEY)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1594, in _reconsolidate
    widget = self._reconsolidate(child_context.root_element_next, "/", new_parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1594, in _reconsolidate
    widget = self._reconsolidate(child_context.root_element_next, "/", new_parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1710, in _reconsolidate
    kwargs = reconsolidate_children()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1678, in reconsolidate_children
    new_kwargs = self._visit_children_values(kwargs, key, parent_key, self._reconsolidate)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in _visit_children_values
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in <dictcomp>
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in _visit_children_values
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in <listcomp>
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1899, in _visit_children_values
    return f(value, key, parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1594, in _reconsolidate
    widget = self._reconsolidate(child_context.root_element_next, "/", new_parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1594, in _reconsolidate
    widget = self._reconsolidate(child_context.root_element_next, "/", new_parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1594, in _reconsolidate
    widget = self._reconsolidate(child_context.root_element_next, "/", new_parent_key)
  [Previous line repeated 1 more time]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1710, in _reconsolidate
    kwargs = reconsolidate_children()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1678, in reconsolidate_children
    new_kwargs = self._visit_children_values(kwargs, key, parent_key, self._reconsolidate)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in _visit_children_values
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in <dictcomp>
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in _visit_children_values
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in <listcomp>
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1899, in _visit_children_values
    return f(value, key, parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1594, in _reconsolidate
    widget = self._reconsolidate(child_context.root_element_next, "/", new_parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1710, in _reconsolidate
    kwargs = reconsolidate_children()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1678, in reconsolidate_children
    new_kwargs = self._visit_children_values(kwargs, key, parent_key, self._reconsolidate)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in _visit_children_values
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in <dictcomp>
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in _visit_children_values
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in <listcomp>
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1899, in _visit_children_values
    return f(value, key, parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1710, in _reconsolidate
    kwargs = reconsolidate_children()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1678, in reconsolidate_children
    new_kwargs = self._visit_children_values(kwargs, key, parent_key, self._reconsolidate)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in _visit_children_values
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in <dictcomp>
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in _visit_children_values
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in <listcomp>
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1899, in _visit_children_values
    return f(value, key, parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1710, in _reconsolidate
    kwargs = reconsolidate_children()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1678, in reconsolidate_children
    new_kwargs = self._visit_children_values(kwargs, key, parent_key, self._reconsolidate)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in _visit_children_values
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in <dictcomp>
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in _visit_children_values
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in <listcomp>
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1899, in _visit_children_values
    return f(value, key, parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1594, in _reconsolidate
    widget = self._reconsolidate(child_context.root_element_next, "/", new_parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1710, in _reconsolidate
    kwargs = reconsolidate_children()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1678, in reconsolidate_children
    new_kwargs = self._visit_children_values(kwargs, key, parent_key, self._reconsolidate)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in _visit_children_values
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in <dictcomp>
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in _visit_children_values
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in <listcomp>
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1899, in _visit_children_values
    return f(value, key, parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1710, in _reconsolidate
    kwargs = reconsolidate_children()
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1678, in reconsolidate_children
    new_kwargs = self._visit_children_values(kwargs, key, parent_key, self._reconsolidate)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in _visit_children_values
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1907, in <dictcomp>
    return {k: self._visit_children_values(v, f"{key}{k}/", parent_key, f) for k, v in value.items()}
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in _visit_children_values
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1902, in <listcomp>
    values = [self._visit_children_values(v, f"{key}{index}/", parent_key, f) for index, v in enumerate(value)]
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1899, in _visit_children_values
    return f(value, key, parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1594, in _reconsolidate
    widget = self._reconsolidate(child_context.root_element_next, "/", new_parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1794, in _reconsolidate
    self._remove_element(self.context.elements[key], key, parent_key=parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1845, in _remove_element
    self._remove_element(self.context.root_element, "/", parent_key=new_parent_key)
  File "/opt/render/project/src/.venv/lib/python3.9/site-packages/reacton/core.py", line 1861, in _remove_element
    assert widget.model_id in widgets.Widget.widgets
AssertionError

```

**Comment by maartenbreddels** [comment]
I did a redeploy, and it seems to work. The only thing I can think of now is that https://github.com/widgetti/reacton/commit/2087adae06478e0a9d15b3afd273d52aac4fd746 fixed it.
If not, we can re-open
