### ISSUE TITLE
Autoreload KeyError: <package_name>

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#334]
I'm having an issue with autoreload on solara v 1.22.0, and I think has the same issue with v1.21.

I have a solara MWE script in `filename.py` and then run with: 

```
solara run package_name.module.filename
```

Traceback:

```
Traceback (most recent call last):
  File "C:\Users\jhsmi\pp\do-fret\.venv\lib\site-packages\solara\server\app.py", line 317, in load_app_widget
    widget, render_context = _run_app(
  File "C:\Users\jhsmi\pp\do-fret\.venv\lib\site-packages\solara\server\app.py", line 265, in _run_app
    main_object = app_script.run()
  File "C:\Users\jhsmi\pp\do-fret\.venv\lib\site-packages\solara\server\app.py", line 198, in run
    self._first_execute_app = self._execute()
  File "C:\Users\jhsmi\pp\do-fret\.venv\lib\site-packages\solara\server\app.py", line 131, in _execute
    spec = importlib.util.find_spec(self.name)
  File "C:\Users\jhsmi\pp\do-fret\.venv\lib\importlib\util.py", line 103, in find_spec
    return _find_spec(fullname, parent_path)
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1389, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in __iter__
  File "<frozen importlib._bootstrap_external>", line 1239, in _recalculate
  File "<frozen importlib._bootstrap_external>", line 1235, in _get_parent_path
KeyError: 'dont_fret'
```

Instead, If i move the file up out of the module, and directly under the package root and run with:

```
solara run package_name.filename
```

I don't have issues with autoreload and it does correctly detect also changes in the dependencies being imported from the module

**Comment by maartenbreddels** [comment]
Do you have an `__init__` in package_name.module ? (what in your case is package_name and module named?)

**Comment by Jhsmit** [comment]
I did not! 
adding it solved my issue
