### ISSUE TITLE
facing thread issue 

### ISSUE THREAD

**Issue by DotKhalid** [widgetti/solara#428]
Exception in thread Thread-1 (_track):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/root/Travel_Assistant/myenv/lib/python3.11/site-packages/solara/server/patch.py", line 258, in Thread_debug_run
    if self.current_context:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Thread' object has no attribute 'current_context'

**Comment by iisakkirotko** [comment]
Hi @DotKhalid!

We're aware of this issue, and will work to have it fixed. In the meantime, your app should continue to work as expected.

**Comment by DotKhalid** [comment]
not working as expected
