### ISSUE TITLE
render loop does not stop for user defined type

### ISSUE THREAD

**Issue by zhuoqiang** [widgetti/solara#472]
it is weired to me that the following code runs ok if `get_data()` return a buildin type, like int, str, or list, etc. 

```python
import pandas as pd
import solara


class Foo:
    pass


def get_data():
    # # ok to return builtin types
    return 1
    # return "hello"
    # return [1, 2]

    # # failed to return user defined type
    # return Foo()
    # return pd.DataFrame()


@solara.component
def Page():
    data = solara.use_reactive(get_data())

    def my_click_handler():
        data.value = get_data()

    button = solara.Button("refresh", on_click=my_click_handler)
    table = solara.Text(f"{data.value}")
```

however, if we return an user defined type, like `pd.DataFrame`, `np.ndarray`, or even `class Foo`, it yields a `RuntimeError`:

```shell
Traceback (most recent call last):
  File "python3.12/site-packages/reacton/ipyvue.py", line 23, in handler
    callback_ref.current(*args)
  File "python3.12/site-packages/solara/components/button.py", line 84, in <lambda>
    ipyvue.use_event(btn, click_event, lambda *_ignore: on_click and on_click())
                                                                     ^^^^^^^^^^
  File "study_solara.py", line 19, in my_click_handler
    data.value = get_data()
    ^^^^^^^^^^
  File "python3.12/site-packages/solara/toestand.py", line 98, in value
    self.set(value)
  File "python3.12/site-packages/solara/toestand.py", line 301, in set
    self._storage.set(value)
  File "python3.12/site-packages/solara/toestand.py", line 255, in set
    self.fire(value, old)
  File "python3.12/site-packages/solara/toestand.py", line 138, in fire
    with contextlib.ExitStack() as stack:
  File "/lib/python3.12/contextlib.py", line 598, in __exit__
    raise exc_details[1]
  File "/lib/python3.12/contextlib.py", line 583, in __exit__
    if cb(*exc_details):
       ^^^^^^^^^^^^^^^^
  File "python3.12/site-packages/reacton/core.py", line 1166, in __exit__
    self._possible_rerender()
  File "python3.12/site-packages/reacton/core.py", line 1363, in _possible_rerender
    self.render(self.element, self.container)
  File "python3.12/site-packages/reacton/core.py", line 1435, in render
    raise RuntimeError(msg)
RuntimeError: Too many renders triggered, your render loop does not stop
Last reason: Reason: state changed with key auto_subscribe_force_update_counter
Value changed from 52 to 53

Previous reasons: Reason: state changed with key auto_subscribe_force_update_counter
Value changed from 51 to 52
```

- python version 3.12
- solara version 1.25.1

**Comment by zhuoqiang** [comment]
I might find the issue: it seems the solara trys to check if the state has been changed by using `==` comparation, which is usually defined for builtin types, but not for user defined types, for example, `pd.DataFrame`.

adding the missing `__eq__` method fix the following code:

```python
import solara


class Foo:
    # have to provide this for solara
    def __eq__(self, other):
        return True


def get_data():
    return Foo()


@solara.component
def Page():
    data = solara.use_reactive(get_data())

    def my_click_handler():
        data.value = get_data()

    button = solara.Button("refresh", on_click=my_click_handler)
    table = solara.Text(f"{data.value}")
```

is there any offical solution for use user defined type like `pd.DataFrame` as state?

- should I check for equality manually before updating the state to stop the infinit loop?
- or is there any way I could pass a customized compare function for a state?

**Comment by zhuoqiang** [comment]
well, I find the less magic `use_state()` works in this case without any user defined euqal method naturely. it just re render the component for once.

```python
import solara


class Foo:
    pass


def get_data():
    return Foo()


@solara.component
def Page():
    # use_state works. no more infinit re render ...
    data, set_data = solara.use_state(get_data())

    def my_click_handler():
        set_data(get_data())

    button = solara.Button("refresh", on_click=my_click_handler)
    table = solara.Text(f"{data}")

```

**Comment by maartenbreddels** [comment]
Hi Zhuo,

thank you for this report. I agree this is maybe not expected given how use_state works. A way around this is:
```
data = solara.use_reactive(solara.use_memo(lambda: get_data()))
```
I've documented this in https://github.com/widgetti/solara/commit/021c2e898909f35fb51bce5af1ab415fca390033

If you feel this is not sufficient, feel free to reopen this issue.

Regards,

Maarten
