### ISSUE TITLE
`lazy` FileDrop raises error reading from `file_obj`

### ISSUE THREAD

**Issue by ntjess** [widgetti/solara#676]
```python
import typing as t
import solara as sl

@sl.component
def Page():
    wired_files, set_wired_files = sl.use_state(t.cast(sl.file_drop.FileInfo, {}))
    sl.FileDrop(on_file=set_wired_files)

    if wired_files:
        sl.Text(f"{wired_files["file_obj"].read(100)=}")
```

This code produces the following error on uploading a file:

```
Traceback (most recent call last):
  File "/Users/ntjess/miniconda3/envs/py312/lib/python3.12/site-packages/reacton/core.py", line 1707, in _render
    root_element = el.component.f(*el.args, **el.kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ntjess/Desktop/terraverum/luminary/luminary/main.py", line 14, in Page
    sl.Text(f"{wired_files["file_obj"].read(100)=}")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ntjess/miniconda3/envs/py312/lib/python3.12/site-packages/ipyvuetify/extra/file_input.py", line 166, in readinto
    nest_asyncio.apply()
  File "/Users/ntjess/miniconda3/envs/py312/lib/python3.12/site-packages/nest_asyncio.py", line 19, in apply
    _patch_loop(loop)
  File "/Users/ntjess/miniconda3/envs/py312/lib/python3.12/site-packages/nest_asyncio.py", line 193, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
```

**Comment by maartenbreddels** [comment]
Hi Nathan,

the problem is that reading from a file in an already running event loop is not supported (unless it can be patched using nest_asycio, but I still wouldn't do that).
A better route is to do this from a thread, which allows your program to stay responsive.
```python
import typing as t
import solara as sl
import  solara.lab




@sl.component
def Page():
    wired_files, set_wired_files = sl.use_state(t.cast(sl.file_drop.FileInfo, {}))

    sl.FileDrop(on_file=set_wired_files)
    def read_file():
        if not wired_files:
            return
        return wired_files['file_obj'].read(100)
    read_file_task = solara.lab.use_task(read_file, dependencies=[wired_files])

    if read_file_task.finished:
        sl.Text(f"{read_file_task.value=}")
    solara.ProgressLinear(read_file_task.pending)
    if read_file_task.error:
        sl.Error(repr(read_file_task.exception))
```

Does this make sense?

**Comment by ntjess** [comment]
This makes perfect sense, thanks!

**Comment by cgodoyle** [comment]
Hi @maartenbreddels, do you know of a similar solution that works for an ipyvuetify.extra.FileInput widget? I have a menu embedded into a ipyleaflet map as a WidgetControl, so I think a Solara component won't work there. The app I'm working on works great in Voila, but I wanted to port it to Solara since it is faster, but I'm stuck with that. The ipywidgets.FileUpload works great but it has this tornado limit that I don't know how to fix with Solara (again, it works great with Voila changing the configuration).
